[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Joe Jackson <cpmhjoe@gmail.com>"]

[dependencies]
chrono = "0.4.6"
regex = "1.1.0"
lazy_static = "1.2.0"
clap = "2.32.0"
structopt = "0.2"
